name: josephcandito.com
favicon: null
layout_spectrum: 0.7377985913772136
typography_spectrum: 0.2159487393219024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.28442018548958004
  lightness: 0.6686308067291975
  saturation: 0.3858481615316123
  rhythmicContrast: 0.6490254926029593
purpose: []
